;*******************************************************************
;*
;*	 PEDasm generated dll import file for file: EVMSIM.asm 
;*
;*
;*



;------------------------------------------------------------
;+
;+	from dll : KERNEL32.dll 
;+

extern	_imp__Sleep : dword
Sleep equ _imp__Sleep

extern	_imp__CloseHandle : dword
CloseHandle equ _imp__CloseHandle

extern	_imp__TerminateThread : dword
TerminateThread equ _imp__TerminateThread

extern	_imp__FindFirstFileA : dword
FindFirstFileA equ _imp__FindFirstFileA

extern	_imp__CreateThread : dword
CreateThread equ _imp__CreateThread

extern	_imp__GetPrivateProfileStringA : dword
GetPrivateProfileStringA equ _imp__GetPrivateProfileStringA

extern	_imp__LocalFree : dword
LocalFree equ _imp__LocalFree

extern	_imp__LocalUnlock : dword
LocalUnlock equ _imp__LocalUnlock

extern	_imp__LocalLock : dword
LocalLock equ _imp__LocalLock

extern	_imp__LocalAlloc : dword
LocalAlloc equ _imp__LocalAlloc

extern	_imp__GetCurrentDirectoryA : dword
GetCurrentDirectoryA equ _imp__GetCurrentDirectoryA

extern	_imp__FreeLibrary : dword
FreeLibrary equ _imp__FreeLibrary

extern	_imp__LoadLibraryA : dword
LoadLibraryA equ _imp__LoadLibraryA

extern	_imp__GetProcAddress : dword
GetProcAddress equ _imp__GetProcAddress

extern	_imp__WaitForSingleObject : dword
WaitForSingleObject equ _imp__WaitForSingleObject

extern	_imp__GetTickCount : dword
GetTickCount equ _imp__GetTickCount

extern	_imp__FindNextFileA : dword
FindNextFileA equ _imp__FindNextFileA

extern	_imp__GetModuleHandleA : dword
GetModuleHandleA equ _imp__GetModuleHandleA

extern	_imp__GetStartupInfoA : dword
GetStartupInfoA equ _imp__GetStartupInfoA

extern	_imp__GetStringTypeA : dword
GetStringTypeA equ _imp__GetStringTypeA

extern	_imp__LCMapStringW : dword
LCMapStringW equ _imp__LCMapStringW

extern	_imp__GetStringTypeW : dword
GetStringTypeW equ _imp__GetStringTypeW

extern	_imp__MultiByteToWideChar : dword
MultiByteToWideChar equ _imp__MultiByteToWideChar

extern	_imp__SetStdHandle : dword
SetStdHandle equ _imp__SetStdHandle

extern	_imp__LCMapStringA : dword
LCMapStringA equ _imp__LCMapStringA

extern	_imp__HeapReAlloc : dword
HeapReAlloc equ _imp__HeapReAlloc

extern	_imp__VirtualAlloc : dword
VirtualAlloc equ _imp__VirtualAlloc

extern	_imp__GetOEMCP : dword
GetOEMCP equ _imp__GetOEMCP

extern	_imp__GetACP : dword
GetACP equ _imp__GetACP

extern	_imp__HeapAlloc : dword
HeapAlloc equ _imp__HeapAlloc

extern	_imp__SetFilePointer : dword
SetFilePointer equ _imp__SetFilePointer

extern	_imp__GetLastError : dword
GetLastError equ _imp__GetLastError

extern	_imp__GetCPInfo : dword
GetCPInfo equ _imp__GetCPInfo

extern	_imp__RtlUnwind : dword
RtlUnwind equ _imp__RtlUnwind

extern	_imp__HeapFree : dword
HeapFree equ _imp__HeapFree

extern	_imp__WriteFile : dword
WriteFile equ _imp__WriteFile

extern	_imp__HeapCreate : dword
HeapCreate equ _imp__HeapCreate

extern	_imp__HeapDestroy : dword
HeapDestroy equ _imp__HeapDestroy

extern	_imp__VirtualFree : dword
VirtualFree equ _imp__VirtualFree

extern	_imp__GetStdHandle : dword
GetStdHandle equ _imp__GetStdHandle

extern	_imp__SetHandleCount : dword
SetHandleCount equ _imp__SetHandleCount

extern	_imp__FlushFileBuffers : dword
FlushFileBuffers equ _imp__FlushFileBuffers

extern	_imp__GetFileType : dword
GetFileType equ _imp__GetFileType

extern	_imp__GetCommandLineA : dword
GetCommandLineA equ _imp__GetCommandLineA

extern	_imp__GetEnvironmentStrings : dword
GetEnvironmentStrings equ _imp__GetEnvironmentStrings

extern	_imp__WideCharToMultiByte : dword
WideCharToMultiByte equ _imp__WideCharToMultiByte

extern	_imp__GetEnvironmentStringsW : dword
GetEnvironmentStringsW equ _imp__GetEnvironmentStringsW

extern	_imp__FreeEnvironmentStringsA : dword
FreeEnvironmentStringsA equ _imp__FreeEnvironmentStringsA

extern	_imp__GetModuleFileNameA : dword
GetModuleFileNameA equ _imp__GetModuleFileNameA

extern	_imp__FreeEnvironmentStringsW : dword
FreeEnvironmentStringsW equ _imp__FreeEnvironmentStringsW

extern	_imp__ExitProcess : dword
ExitProcess equ _imp__ExitProcess

extern	_imp__GetVersion : dword
GetVersion equ _imp__GetVersion

extern	_imp__UnhandledExceptionFilter : dword
UnhandledExceptionFilter equ _imp__UnhandledExceptionFilter

extern	_imp__GetCurrentProcess : dword
GetCurrentProcess equ _imp__GetCurrentProcess

extern	_imp__TerminateProcess : dword
TerminateProcess equ _imp__TerminateProcess



;------------------------------------------------------------
;+
;+	from dll : USER32.dll 
;+

extern	_imp__GetWindowRect : dword
GetWindowRect equ _imp__GetWindowRect

extern	_imp__MessageBoxA : dword
MessageBoxA equ _imp__MessageBoxA

extern	_imp__wsprintfA : dword
wsprintfA equ _imp__wsprintfA

extern	_imp__GetMessageA : dword
GetMessageA equ _imp__GetMessageA

extern	_imp__DispatchMessageA : dword
DispatchMessageA equ _imp__DispatchMessageA

extern	_imp__TranslateMessage : dword
TranslateMessage equ _imp__TranslateMessage

extern	_imp__SetTimer : dword
SetTimer equ _imp__SetTimer

extern	_imp__UpdateWindow : dword
UpdateWindow equ _imp__UpdateWindow

extern	_imp__SetDlgItemTextA : dword
SetDlgItemTextA equ _imp__SetDlgItemTextA

extern	_imp__SendMessageA : dword
SendMessageA equ _imp__SendMessageA

extern	_imp__SendDlgItemMessageA : dword
SendDlgItemMessageA equ _imp__SendDlgItemMessageA

extern	_imp__CreatePopupMenu : dword
CreatePopupMenu equ _imp__CreatePopupMenu

extern	_imp__GetSystemMetrics : dword
GetSystemMetrics equ _imp__GetSystemMetrics

extern	_imp__SetWindowPos : dword
SetWindowPos equ _imp__SetWindowPos

extern	_imp__GetCursorPos : dword
GetCursorPos equ _imp__GetCursorPos

extern	_imp__AppendMenuA : dword
AppendMenuA equ _imp__AppendMenuA

extern	_imp__EnableMenuItem : dword
EnableMenuItem equ _imp__EnableMenuItem

extern	_imp__PostMessageA : dword
PostMessageA equ _imp__PostMessageA

extern	_imp__TrackPopupMenu : dword
TrackPopupMenu equ _imp__TrackPopupMenu

extern	_imp__PostQuitMessage : dword
PostQuitMessage equ _imp__PostQuitMessage

extern	_imp__GetClientRect : dword
GetClientRect equ _imp__GetClientRect

extern	_imp__BeginPaint : dword
BeginPaint equ _imp__BeginPaint

extern	_imp__LoadBitmapA : dword
LoadBitmapA equ _imp__LoadBitmapA

extern	_imp__DestroyMenu : dword
DestroyMenu equ _imp__DestroyMenu

extern	_imp__EndPaint : dword
EndPaint equ _imp__EndPaint

extern	_imp__GetAsyncKeyState : dword
GetAsyncKeyState equ _imp__GetAsyncKeyState

extern	_imp__KillTimer : dword
KillTimer equ _imp__KillTimer

extern	_imp__DestroyWindow : dword
DestroyWindow equ _imp__DestroyWindow

extern	_imp__DefWindowProcA : dword
DefWindowProcA equ _imp__DefWindowProcA

extern	_imp__RegisterClassA : dword
RegisterClassA equ _imp__RegisterClassA

extern	_imp__LoadIconA : dword
LoadIconA equ _imp__LoadIconA

extern	_imp__LoadCursorA : dword
LoadCursorA equ _imp__LoadCursorA

extern	_imp__ShowWindow : dword
ShowWindow equ _imp__ShowWindow

extern	_imp__LoadMenuA : dword
LoadMenuA equ _imp__LoadMenuA

extern	_imp__CreateWindowExA : dword
CreateWindowExA equ _imp__CreateWindowExA

extern	_imp__CreateDialogParamA : dword
CreateDialogParamA equ _imp__CreateDialogParamA



;------------------------------------------------------------
;+
;+	from dll : GDI32.dll 
;+

extern	_imp__DeleteDC : dword
DeleteDC equ _imp__DeleteDC

extern	_imp__StretchBlt : dword
StretchBlt equ _imp__StretchBlt

extern	_imp__GetStockObject : dword
GetStockObject equ _imp__GetStockObject

extern	_imp__CreateCompatibleDC : dword
CreateCompatibleDC equ _imp__CreateCompatibleDC

extern	_imp__GetObjectA : dword
GetObjectA equ _imp__GetObjectA

extern	_imp__SelectObject : dword
SelectObject equ _imp__SelectObject

